//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorCO2MapAppV2.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndoorCO2MapAppV2.Resources.Strings.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel Recording ähnelt.
        /// </summary>
        internal static string CancelRecordingButton {
            get {
                return ResourceManager.GetString("CancelRecordingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CO2 Levels:  ähnelt.
        /// </summary>
        internal static string CO2LevelsLabel {
            get {
                return ResourceManager.GetString("CO2LevelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current CO2:  ähnelt.
        /// </summary>
        internal static string CurrentCOLevelsLabel {
            get {
                return ResourceManager.GetString("CurrentCOLevelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export failed ähnelt.
        /// </summary>
        internal static string HistoryExportDatabaseFailure {
            get {
                return ResourceManager.GetString("HistoryExportDatabaseFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export completed ähnelt.
        /// </summary>
        internal static string HistoryExportDatabaseSuccess {
            get {
                return ResourceManager.GetString("HistoryExportDatabaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export to File ähnelt.
        /// </summary>
        internal static string HistoryExportDatabaseTitle {
            get {
                return ResourceManager.GetString("HistoryExportDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not import the database. Please try again. ähnelt.
        /// </summary>
        internal static string HistoryImportDatabaseFailureDescription {
            get {
                return ResourceManager.GetString("HistoryImportDatabaseFailureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Failed ähnelt.
        /// </summary>
        internal static string HistoryImportDatabaseFailureTitle {
            get {
                return ResourceManager.GetString("HistoryImportDatabaseFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database imported successfully. Please restart the app to load the new database. ähnelt.
        /// </summary>
        internal static string HistoryImportDatabaseSuccessfulDescription {
            get {
                return ResourceManager.GetString("HistoryImportDatabaseSuccessfulDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Successful ähnelt.
        /// </summary>
        internal static string HistoryImportDatabaseSuccessfulTitle {
            get {
                return ResourceManager.GetString("HistoryImportDatabaseSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Building Recording ähnelt.
        /// </summary>
        internal static string MainMenuButtonStartBuildingRecording {
            get {
                return ResourceManager.GetString("MainMenuButtonStartBuildingRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History ähnelt.
        /// </summary>
        internal static string MainMenuHistoryButtonText {
            get {
                return ResourceManager.GetString("MainMenuHistoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable 15 minutes prerecording ähnelt.
        /// </summary>
        internal static string MainMenuPrerecordingSwitchText {
            get {
                return ResourceManager.GetString("MainMenuPrerecordingSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search by name... ähnelt.
        /// </summary>
        internal static string MainMenuResultFilterPlaceholderText {
            get {
                return ResourceManager.GetString("MainMenuResultFilterPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string MainMenuSettingsButtonText {
            get {
                return ResourceManager.GetString("MainMenuSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select your CO2-Monitor ähnelt.
        /// </summary>
        internal static string MonitorSelectionLabel {
            get {
                return ResourceManager.GetString("MonitorSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Sensor Found ähnelt.
        /// </summary>
        internal static string NoSensorFoundStatusLabel {
            get {
                return ResourceManager.GetString("NoSensorFoundStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Doors / Windows ähnelt.
        /// </summary>
        internal static string RadioButtonLabelOpenDoorsWindows {
            get {
                return ResourceManager.GetString("RadioButtonLabelOpenDoorsWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ventilation System ähnelt.
        /// </summary>
        internal static string RadioButtonLabelVentilationSystem {
            get {
                return ResourceManager.GetString("RadioButtonLabelVentilationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Note ähnelt.
        /// </summary>
        internal static string RecordingCustomNoteLabelText {
            get {
                return ResourceManager.GetString("RecordingCustomNoteLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add a note about this measurement... ähnelt.
        /// </summary>
        internal static string RecordingCustomNotPlaceholderText {
            get {
                return ResourceManager.GetString("RecordingCustomNotPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location:  ähnelt.
        /// </summary>
        internal static string RecordingLocationLabel {
            get {
                return ResourceManager.GetString("RecordingLocationLabel", resourceCulture);
            }
        }

        internal static string RecordingNextUpdateLabel {
            get {
                return ResourceManager.GetString("RecordingNextUpdateLabel", resourceCulture);
            }
        }

        internal static string RecoveryAbortButton {
            get {
                return ResourceManager.GetString("RecoveryAbortButton", resourceCulture);
            }
        }

        internal static string RecoveryWaitingForInit {
            get {
                return ResourceManager.GetString("RecoveryWaitingForInit", resourceCulture);
            }
        }

        internal static string RecoveryOpeningRecording {
            get {
                return ResourceManager.GetString("RecoveryOpeningRecording", resourceCulture);
            }
        }

        internal static string RecoverySearchingWithTimeLeft {
            get {
                return ResourceManager.GetString("RecoverySearchingWithTimeLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning for devices... ähnelt.
        /// </summary>
        internal static string ScanningStatusLabel {
            get {
                return ResourceManager.GetString("ScanningStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search Buildings ähnelt.
        /// </summary>
        internal static string SearchBuildingButtonLabel_Ready {
            get {
                return ResourceManager.GetString("SearchBuildingButtonLabel_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retrieving Location Data... ähnelt.
        /// </summary>
        internal static string SearchBuildingButtonLabel_Searching {
            get {
                return ResourceManager.GetString("SearchBuildingButtonLabel_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search Range:  ähnelt.
        /// </summary>
        internal static string SearchRangeLabel {
            get {
                return ResourceManager.GetString("SearchRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alphabetical ähnelt.
        /// </summary>
        internal static string Sort_Alphabetical {
            get {
                return ResourceManager.GetString("Sort_Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance ähnelt.
        /// </summary>
        internal static string Sort_Distance {
            get {
                return ResourceManager.GetString("Sort_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit Recording ähnelt.
        /// </summary>
        internal static string SubmitRecordingButton {
            get {
                return ResourceManager.GetString("SubmitRecordingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}/5 data points needed to submit ähnelt.
        /// </summary>
        internal static string SubmitRecordingButtonNeedData {
            get {
                return ResourceManager.GetString("SubmitRecordingButtonNeedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Interval:  ähnelt.
        /// </summary>
        internal static string UpdateInterval {
            get {
                return ResourceManager.GetString("UpdateInterval", resourceCulture);
            }
        }

        internal static string SettingsLanguageRestartHint {
            get {
                return ResourceManager.GetString("SettingsLanguageRestartHint", resourceCulture);
            }
        }

        internal static string MainMenuModeBuilding {
            get { return ResourceManager.GetString("MainMenuModeBuilding", resourceCulture); }
        }

        internal static string MainMenuModeTransit {
            get { return ResourceManager.GetString("MainMenuModeTransit", resourceCulture); }
        }

        internal static string MainMenuButtonStartTransitRecording {
            get { return ResourceManager.GetString("MainMenuButtonStartTransitRecording", resourceCulture); }
        }

        internal static string MainMenuBlockedNoBuilding {
            get { return ResourceManager.GetString("MainMenuBlockedNoBuilding", resourceCulture); }
        }

        internal static string MainMenuBlockedNoSensor {
            get { return ResourceManager.GetString("MainMenuBlockedNoSensor", resourceCulture); }
        }

        internal static string MainMenuBlockedWaitingCO2 {
            get { return ResourceManager.GetString("MainMenuBlockedWaitingCO2", resourceCulture); }
        }

        internal static string MainMenuBlockedNoStation {
            get { return ResourceManager.GetString("MainMenuBlockedNoStation", resourceCulture); }
        }

        internal static string MainMenuBlockedNoRoute {
            get { return ResourceManager.GetString("MainMenuBlockedNoRoute", resourceCulture); }
        }
        internal static string RadioYes { get { return ResourceManager.GetString("RadioYes", resourceCulture); } }
        internal static string RadioNo { get { return ResourceManager.GetString("RadioNo", resourceCulture); } }
        internal static string RadioNoData { get { return ResourceManager.GetString("RadioNoData", resourceCulture); } }
        internal static string TransitDestinationLabel { get { return ResourceManager.GetString("TransitDestinationLabel", resourceCulture); } }
        internal static string TransitSearchNearbyStops { get { return ResourceManager.GetString("TransitSearchNearbyStops", resourceCulture); } }
        internal static string TransitSelectDestination { get { return ResourceManager.GetString("TransitSelectDestination", resourceCulture); } }
        internal static string TransitRouteStationPlaceholder { get { return ResourceManager.GetString("TransitRouteStationPlaceholder", resourceCulture); } }
        internal static string MainMenuResumingRecording { get { return ResourceManager.GetString("MainMenuResumingRecording", resourceCulture); } }
        internal static string MainMenuSubmissionSuccessful { get { return ResourceManager.GetString("MainMenuSubmissionSuccessful", resourceCulture); } }
        internal static string MainMenuResumeRecording { get { return ResourceManager.GetString("MainMenuResumeRecording", resourceCulture); } }
        internal static string MainMenuRoutePreview { get { return ResourceManager.GetString("MainMenuRoutePreview", resourceCulture); } }
        internal static string MainMenuNewsButton { get { return ResourceManager.GetString("MainMenuNewsButton", resourceCulture); } }
        internal static string SettingsShowNewsNotification { get { return ResourceManager.GetString("SettingsShowNewsNotification", resourceCulture); } }
        internal static string MainMenuStatisticsButton { get { return ResourceManager.GetString("MainMenuStatisticsButton", resourceCulture); } }
        internal static string MainMenuOpenMapInBrowser { get { return ResourceManager.GetString("MainMenuOpenMapInBrowser", resourceCulture); } }
        internal static string MainMenuDataProtectionImprint { get { return ResourceManager.GetString("MainMenuDataProtectionImprint", resourceCulture); } }
        internal static string MainMenuManualButton { get { return ResourceManager.GetString("MainMenuManualButton", resourceCulture); } }
        internal static string MainMenuDiscordButton { get { return ResourceManager.GetString("MainMenuDiscordButton", resourceCulture); } }
        internal static string TransitSearchRoutesByName { get { return ResourceManager.GetString("TransitSearchRoutesByName", resourceCulture); } }
        internal static string HistoryFilterPlaceholder { get { return ResourceManager.GetString("HistoryFilterPlaceholder", resourceCulture); } }
        internal static string HistoryGroupByLocation { get { return ResourceManager.GetString("HistoryGroupByLocation", resourceCulture); } }
        internal static string HistorySortAZ { get { return ResourceManager.GetString("HistorySortAZ", resourceCulture); } }
        internal static string HistoryRecordingsCount { get { return ResourceManager.GetString("HistoryRecordingsCount", resourceCulture); } }
        internal static string HistoryPpmAvg { get { return ResourceManager.GetString("HistoryPpmAvg", resourceCulture); } }
        internal static string HistoryDeleteTitle { get { return ResourceManager.GetString("HistoryDeleteTitle", resourceCulture); } }
        internal static string HistoryDeleteConfirmOnline { get { return ResourceManager.GetString("HistoryDeleteConfirmOnline", resourceCulture); } }
        internal static string HistoryDeleteConfirmLocal { get { return ResourceManager.GetString("HistoryDeleteConfirmLocal", resourceCulture); } }
        internal static string HistoryDeleteButton { get { return ResourceManager.GetString("HistoryDeleteButton", resourceCulture); } }
        internal static string HistoryCancelButton { get { return ResourceManager.GetString("HistoryCancelButton", resourceCulture); } }
        internal static string TimeAgoJustNow { get { return ResourceManager.GetString("TimeAgoJustNow", resourceCulture); } }
        internal static string TimeAgoToday { get { return ResourceManager.GetString("TimeAgoToday", resourceCulture); } }
        internal static string TimeAgoYesterday { get { return ResourceManager.GetString("TimeAgoYesterday", resourceCulture); } }
        internal static string TimeAgoDaysAgo { get { return ResourceManager.GetString("TimeAgoDaysAgo", resourceCulture); } }
        internal static string TimeAgoOneWeekAgo { get { return ResourceManager.GetString("TimeAgoOneWeekAgo", resourceCulture); } }
        internal static string TimeAgoWeeksAgo { get { return ResourceManager.GetString("TimeAgoWeeksAgo", resourceCulture); } }
        internal static string TimeAgoOneMonthAgo { get { return ResourceManager.GetString("TimeAgoOneMonthAgo", resourceCulture); } }
        internal static string TimeAgoMonthsAgo { get { return ResourceManager.GetString("TimeAgoMonthsAgo", resourceCulture); } }
        internal static string TimeAgoOneYearAgo { get { return ResourceManager.GetString("TimeAgoOneYearAgo", resourceCulture); } }
        internal static string TimeAgoYearsAgo { get { return ResourceManager.GetString("TimeAgoYearsAgo", resourceCulture); } }
        internal static string ContextWindowsOpen { get { return ResourceManager.GetString("ContextWindowsOpen", resourceCulture); } }
        internal static string ContextWindowsClosed { get { return ResourceManager.GetString("ContextWindowsClosed", resourceCulture); } }
        internal static string ContextVentilated { get { return ResourceManager.GetString("ContextVentilated", resourceCulture); } }
        internal static string ContextNotVentilated { get { return ResourceManager.GetString("ContextNotVentilated", resourceCulture); } }
        internal static string HistoryStatsLine { get { return ResourceManager.GetString("HistoryStatsLine", resourceCulture); } }
        internal static string HistoryNoData { get { return ResourceManager.GetString("HistoryNoData", resourceCulture); } }
        internal static string HistoryNoRecordingsYet { get { return ResourceManager.GetString("HistoryNoRecordingsYet", resourceCulture); } }
        internal static string TransitSearchButton { get { return ResourceManager.GetString("TransitSearchButton", resourceCulture); } }
        internal static string TransitSearchingButton { get { return ResourceManager.GetString("TransitSearchingButton", resourceCulture); } }
        internal static string TransitModeAll { get { return ResourceManager.GetString("TransitModeAll", resourceCulture); } }
        internal static string TransitModeBus { get { return ResourceManager.GetString("TransitModeBus", resourceCulture); } }
        internal static string TransitModeTram { get { return ResourceManager.GetString("TransitModeTram", resourceCulture); } }
        internal static string TransitModeTrain { get { return ResourceManager.GetString("TransitModeTrain", resourceCulture); } }
        internal static string TransitModeLightRail { get { return ResourceManager.GetString("TransitModeLightRail", resourceCulture); } }
        internal static string TransitModeSubway { get { return ResourceManager.GetString("TransitModeSubway", resourceCulture); } }
        internal static string SensorWaitingForData { get { return ResourceManager.GetString("SensorWaitingForData", resourceCulture); } }
        internal static string SmartHomeStep1 { get { return ResourceManager.GetString("SmartHomeStep1", resourceCulture); } }
        internal static string SmartHomeStep2 { get { return ResourceManager.GetString("SmartHomeStep2", resourceCulture); } }
        internal static string SmartHomeStep3 { get { return ResourceManager.GetString("SmartHomeStep3", resourceCulture); } }
        internal static string SmartHomeClose { get { return ResourceManager.GetString("SmartHomeClose", resourceCulture); } }
        internal static string NotificationRecordingTitle { get { return ResourceManager.GetString("NotificationRecordingTitle", resourceCulture); } }
        internal static string NotificationChannelDescription { get { return ResourceManager.GetString("NotificationChannelDescription", resourceCulture); } }
        internal static string NotificationRecordingTapToReturn { get { return ResourceManager.GetString("NotificationRecordingTapToReturn", resourceCulture); } }
        internal static string CommonMainMenuButton { get { return ResourceManager.GetString("CommonMainMenuButton", resourceCulture); } }
        internal static string CommonLoading { get { return ResourceManager.GetString("CommonLoading", resourceCulture); } }
        internal static string DialogYes { get { return ResourceManager.GetString("DialogYes", resourceCulture); } }
        internal static string DialogNo { get { return ResourceManager.GetString("DialogNo", resourceCulture); } }
        internal static string DialogCancel { get { return ResourceManager.GetString("DialogCancel", resourceCulture); } }
        internal static string DialogCancelMeasurementTitle { get { return ResourceManager.GetString("DialogCancelMeasurementTitle", resourceCulture); } }
        internal static string DialogCancelMeasurementMessage { get { return ResourceManager.GetString("DialogCancelMeasurementMessage", resourceCulture); } }
        internal static string DialogSubmitMeasurementTitle { get { return ResourceManager.GetString("DialogSubmitMeasurementTitle", resourceCulture); } }
        internal static string DialogSubmitMeasurementMessage { get { return ResourceManager.GetString("DialogSubmitMeasurementMessage", resourceCulture); } }
        internal static string DialogUploadFailedTitle { get { return ResourceManager.GetString("DialogUploadFailedTitle", resourceCulture); } }
        internal static string DialogUploadFailedMessage { get { return ResourceManager.GetString("DialogUploadFailedMessage", resourceCulture); } }
        internal static string DialogUploadErrorMessage { get { return ResourceManager.GetString("DialogUploadErrorMessage", resourceCulture); } }
        internal static string SubmittingDataButton { get { return ResourceManager.GetString("SubmittingDataButton", resourceCulture); } }
        internal static string DialogNoSensorTitle { get { return ResourceManager.GetString("DialogNoSensorTitle", resourceCulture); } }
        internal static string DialogNoSensorMessage { get { return ResourceManager.GetString("DialogNoSensorMessage", resourceCulture); } }
        internal static string DialogSensorNotReadyTitle { get { return ResourceManager.GetString("DialogSensorNotReadyTitle", resourceCulture); } }
        internal static string DialogSensorNotReadyMessage { get { return ResourceManager.GetString("DialogSensorNotReadyMessage", resourceCulture); } }
        internal static string DialogDeleteHistoryTitle { get { return ResourceManager.GetString("DialogDeleteHistoryTitle", resourceCulture); } }
        internal static string DialogDeleteHistoryMessage { get { return ResourceManager.GetString("DialogDeleteHistoryMessage", resourceCulture); } }
        internal static string DialogDeleteLocationCacheMessage { get { return ResourceManager.GetString("DialogDeleteLocationCacheMessage", resourceCulture); } }
        internal static string DialogPrivacyWarningTitle { get { return ResourceManager.GetString("DialogPrivacyWarningTitle", resourceCulture); } }
        internal static string DialogPrivacyWarningMessage { get { return ResourceManager.GetString("DialogPrivacyWarningMessage", resourceCulture); } }
        internal static string DialogDisableRoundingConfirm { get { return ResourceManager.GetString("DialogDisableRoundingConfirm", resourceCulture); } }
        internal static string SettingsSectionLanguage { get { return ResourceManager.GetString("SettingsSectionLanguage", resourceCulture); } }
        internal static string SettingsAppLanguage { get { return ResourceManager.GetString("SettingsAppLanguage", resourceCulture); } }
        internal static string SettingsSectionSensorFilter { get { return ResourceManager.GetString("SettingsSectionSensorFilter", resourceCulture); } }
        internal static string SettingsSensorFilterPlaceholder { get { return ResourceManager.GetString("SettingsSensorFilterPlaceholder", resourceCulture); } }
        internal static string SettingsSectionDisplay { get { return ResourceManager.GetString("SettingsSectionDisplay", resourceCulture); } }
        internal static string SettingsShowSortingToggle { get { return ResourceManager.GetString("SettingsShowSortingToggle", resourceCulture); } }
        internal static string SettingsShowBuildingFilter { get { return ResourceManager.GetString("SettingsShowBuildingFilter", resourceCulture); } }
        internal static string SettingsDefaultSortMode { get { return ResourceManager.GetString("SettingsDefaultSortMode", resourceCulture); } }
        internal static string SettingsShowWebsiteButton { get { return ResourceManager.GetString("SettingsShowWebsiteButton", resourceCulture); } }
        internal static string SettingsShowImprintButton { get { return ResourceManager.GetString("SettingsShowImprintButton", resourceCulture); } }
        internal static string SettingsShowManualButton { get { return ResourceManager.GetString("SettingsShowManualButton", resourceCulture); } }
        internal static string SettingsShowDiscordButton { get { return ResourceManager.GetString("SettingsShowDiscordButton", resourceCulture); } }
        internal static string SettingsShowRoutePreview { get { return ResourceManager.GetString("SettingsShowRoutePreview", resourceCulture); } }
        internal static string SettingsShowChangeRoute { get { return ResourceManager.GetString("SettingsShowChangeRoute", resourceCulture); } }
        internal static string SettingsSectionRecording { get { return ResourceManager.GetString("SettingsSectionRecording", resourceCulture); } }
        internal static string SettingsConfirmBeforeSubmit { get { return ResourceManager.GetString("SettingsConfirmBeforeSubmit", resourceCulture); } }
        internal static string SettingsAllowStartWithoutSensorData { get { return ResourceManager.GetString("SettingsAllowStartWithoutSensorData", resourceCulture); } }
        internal static string SettingsKeepRecordingInBackground { get { return ResourceManager.GetString("SettingsKeepRecordingInBackground", resourceCulture); } }
        internal static string SettingsSectionData { get { return ResourceManager.GetString("SettingsSectionData", resourceCulture); } }
        internal static string SettingsUseLiveLocationService { get { return ResourceManager.GetString("SettingsUseLiveLocationService", resourceCulture); } }
        internal static string SettingsEnableLocationCaching { get { return ResourceManager.GetString("SettingsEnableLocationCaching", resourceCulture); } }
        internal static string SettingsCacheRangeOverride { get { return ResourceManager.GetString("SettingsCacheRangeOverride", resourceCulture); } }
        internal static string SettingsEnableHistory { get { return ResourceManager.GetString("SettingsEnableHistory", resourceCulture); } }
        internal static string SettingsDeleteLocationCache { get { return ResourceManager.GetString("SettingsDeleteLocationCache", resourceCulture); } }
        internal static string SettingsDeleteHistory { get { return ResourceManager.GetString("SettingsDeleteHistory", resourceCulture); } }
        internal static string SettingsSectionDebug { get { return ResourceManager.GetString("SettingsSectionDebug", resourceCulture); } }
        internal static string SettingsRoundGps { get { return ResourceManager.GetString("SettingsRoundGps", resourceCulture); } }
        internal static string SettingsCopyDebugLog { get { return ResourceManager.GetString("SettingsCopyDebugLog", resourceCulture); } }
        internal static string MainMenuTitle { get { return ResourceManager.GetString("MainMenuTitle", resourceCulture); } }
        internal static string MainMenuFetchingData { get { return ResourceManager.GetString("MainMenuFetchingData", resourceCulture); } }
        internal static string MainMenuSmartHomeNotEnabled { get { return ResourceManager.GetString("MainMenuSmartHomeNotEnabled", resourceCulture); } }
        internal static string TransitSelectRoute { get { return ResourceManager.GetString("TransitSelectRoute", resourceCulture); } }
        internal static string TransitMeasurementTitle { get { return ResourceManager.GetString("TransitMeasurementTitle", resourceCulture); } }
        internal static string TransitLineLabel { get { return ResourceManager.GetString("TransitLineLabel", resourceCulture); } }
        internal static string TransitSearchRoutesNearMe { get { return ResourceManager.GetString("TransitSearchRoutesNearMe", resourceCulture); } }
        internal static string TransitApplyRouteChange { get { return ResourceManager.GetString("TransitApplyRouteChange", resourceCulture); } }
        internal static string TransitNoGpsPosition { get { return ResourceManager.GetString("TransitNoGpsPosition", resourceCulture); } }
        internal static string TransitNoStopsNearby { get { return ResourceManager.GetString("TransitNoStopsNearby", resourceCulture); } }
        internal static string TransitSearchFailed { get { return ResourceManager.GetString("TransitSearchFailed", resourceCulture); } }
        internal static string TransitNoCachedStopsNearby { get { return ResourceManager.GetString("TransitNoCachedStopsNearby", resourceCulture); } }
        internal static string TransitCacheLoadFailed { get { return ResourceManager.GetString("TransitCacheLoadFailed", resourceCulture); } }
        internal static string MapPageTitle { get { return ResourceManager.GetString("MapPageTitle", resourceCulture); } }
        internal static string MapBackToHistory { get { return ResourceManager.GetString("MapBackToHistory", resourceCulture); } }
        internal static string MapReloadTiles { get { return ResourceManager.GetString("MapReloadTiles", resourceCulture); } }
        internal static string MapFilterBuildings { get { return ResourceManager.GetString("MapFilterBuildings", resourceCulture); } }
        internal static string MapShowLabels { get { return ResourceManager.GetString("MapShowLabels", resourceCulture); } }
        internal static string MapNotAvailableWindows { get { return ResourceManager.GetString("MapNotAvailableWindows", resourceCulture); } }
        internal static string HistoryExportData { get { return ResourceManager.GetString("HistoryExportData", resourceCulture); } }
        internal static string HistoryImportData { get { return ResourceManager.GetString("HistoryImportData", resourceCulture); } }
        internal static string StatisticsCommunityStats { get { return ResourceManager.GetString("StatisticsCommunityStats", resourceCulture); } }
        internal static string StatisticsMeasurementsByCountry { get { return ResourceManager.GetString("StatisticsMeasurementsByCountry", resourceCulture); } }
        internal static string StatisticsColumnCountry { get { return ResourceManager.GetString("StatisticsColumnCountry", resourceCulture); } }
        internal static string StatisticsColumnCount { get { return ResourceManager.GetString("StatisticsColumnCount", resourceCulture); } }
        internal static string StatusGpsStatus { get { return ResourceManager.GetString("StatusGpsStatus", resourceCulture); } }
        internal static string StatusGpsPermissions { get { return ResourceManager.GetString("StatusGpsPermissions", resourceCulture); } }
        internal static string StatusBtStatus { get { return ResourceManager.GetString("StatusBtStatus", resourceCulture); } }
        internal static string StatusBtPermissions { get { return ResourceManager.GetString("StatusBtPermissions", resourceCulture); } }
        internal static string StatusAllReady { get { return ResourceManager.GetString("StatusAllReady", resourceCulture); } }
    }
}
